// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory-item-write/proto/item_events.proto

package itemEvents

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemAdded struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemAdded) Reset()         { *m = ItemAdded{} }
func (m *ItemAdded) String() string { return proto.CompactTextString(m) }
func (*ItemAdded) ProtoMessage()    {}
func (*ItemAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_events_73d22b4e7d629583, []int{0}
}
func (m *ItemAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAdded.Unmarshal(m, b)
}
func (m *ItemAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAdded.Marshal(b, m, deterministic)
}
func (dst *ItemAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAdded.Merge(dst, src)
}
func (m *ItemAdded) XXX_Size() int {
	return xxx_messageInfo_ItemAdded.Size(m)
}
func (m *ItemAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAdded.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAdded proto.InternalMessageInfo

func (m *ItemAdded) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ItemAdded) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ItemUpdated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemUpdated) Reset()         { *m = ItemUpdated{} }
func (m *ItemUpdated) String() string { return proto.CompactTextString(m) }
func (*ItemUpdated) ProtoMessage()    {}
func (*ItemUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_events_73d22b4e7d629583, []int{1}
}
func (m *ItemUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemUpdated.Unmarshal(m, b)
}
func (m *ItemUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemUpdated.Marshal(b, m, deterministic)
}
func (dst *ItemUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemUpdated.Merge(dst, src)
}
func (m *ItemUpdated) XXX_Size() int {
	return xxx_messageInfo_ItemUpdated.Size(m)
}
func (m *ItemUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ItemUpdated proto.InternalMessageInfo

func (m *ItemUpdated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ItemUpdated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ItemDeleted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemDeleted) Reset()         { *m = ItemDeleted{} }
func (m *ItemDeleted) String() string { return proto.CompactTextString(m) }
func (*ItemDeleted) ProtoMessage()    {}
func (*ItemDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_events_73d22b4e7d629583, []int{2}
}
func (m *ItemDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDeleted.Unmarshal(m, b)
}
func (m *ItemDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDeleted.Marshal(b, m, deterministic)
}
func (dst *ItemDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDeleted.Merge(dst, src)
}
func (m *ItemDeleted) XXX_Size() int {
	return xxx_messageInfo_ItemDeleted.Size(m)
}
func (m *ItemDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDeleted proto.InternalMessageInfo

func (m *ItemDeleted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ItemAdded)(nil), "itemEvents.ItemAdded")
	proto.RegisterType((*ItemUpdated)(nil), "itemEvents.ItemUpdated")
	proto.RegisterType((*ItemDeleted)(nil), "itemEvents.ItemDeleted")
}

func init() {
	proto.RegisterFile("inventory-item-write/proto/item_events.proto", fileDescriptor_item_events_73d22b4e7d629583)
}

var fileDescriptor_item_events_73d22b4e7d629583 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc9, 0xcc, 0x2b, 0x4b,
	0xcd, 0x2b, 0xc9, 0x2f, 0xaa, 0xd4, 0xcd, 0x2c, 0x49, 0xcd, 0xd5, 0x2d, 0x2f, 0xca, 0x2c, 0x49,
	0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0x09, 0xc4, 0xa7, 0x82, 0xa4, 0x8b, 0xf5, 0xc0,
	0x22, 0x42, 0x5c, 0x20, 0x21, 0x57, 0xb0, 0x88, 0x92, 0x3e, 0x17, 0xa7, 0x67, 0x49, 0x6a, 0xae,
	0x63, 0x4a, 0x4a, 0x6a, 0x8a, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58,
	0x04, 0xcc, 0x56, 0x32, 0xe4, 0xe2, 0x06, 0x69, 0x08, 0x2d, 0x48, 0x49, 0x2c, 0x21, 0x52, 0x8b,
	0x2c, 0x44, 0x8b, 0x4b, 0x6a, 0x4e, 0x2a, 0x16, 0x2d, 0x49, 0x6c, 0x60, 0x57, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0xb9, 0x56, 0xeb, 0xc5, 0x00, 0x00, 0x00,
}
